## NumPy (Numerical Python)

    NumPy stands for Numerical Python. 
    It is a fundamental/ core library needed for scientific computing with Python, which adds support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

## Remember to Install Numpy 
pip install numpy


    In the first cell we put the code to import the numpy library as np. 
    This is for convenience; every time we need to use some functionality from the numpy library, we will write np instead of numpy.

In [70]:
import numpy as np

In [71]:
np.__version__

'1.20.3'

### The Basics

In [72]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [73]:
# To check the size of an array
# For dtype=int32 = 96 + n * 4 Bytes => a = [1,2,3] => 96 + 3 * 4 = 108 
# For dtype=int64 = 96 + n * 8 Bytes => a = [1,2,3] => 96 + 3 * 8 = 120
# Whereas, 96 Bytes are allocated for other information of the array object (shape, dimension etc.).

import sys
sys.getsizeof(a)

116

In [74]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [75]:
# Get Dimension
b.ndim

2

In [76]:
# Get Shape
b.shape

(2, 3)

In [77]:
a = np.array(
                [   [  [ [1,1], [2,2] ],  [ [3,3], [4,4] ]  ],
    
                    [  [ [5,5], [6,6] ],  [ [7,7], [8,8] ]  ]   ])


In [78]:
print("Dimensions: ", a.ndim)
print("Shape     : ", a.shape)

Dimensions:  4
Shape     :  (2, 2, 2, 2)


In [79]:
# Get Type
a.dtype

dtype('int64')

In [80]:
# Get Size (Size of one value i.e. size of one value of dtype='int64' = 8)
a.itemsize

8

In [12]:
# Get total size
a.nbytes

128

In [13]:
# Get number of elements
a.size

16

In [89]:
practice = np.array ([[[[1,1],[2,2]] , [[3,3],[4,4]],[[1,1],[2,2]] , [[3,3],[4,4]]]])

In [90]:
practice

array([[[[1, 1],
         [2, 2]],

        [[3, 3],
         [4, 4]],

        [[1, 1],
         [2, 2]],

        [[3, 3],
         [4, 4]]]])

In [91]:
print("Dimentions: ", practice.ndim)
print("Shape: ", practice.shape)

Dimentions:  4
Shape:  (1, 4, 2, 2)


In [92]:
practice.dtype

dtype('int64')

In [93]:
practice.itemsize

8

In [94]:
practice.size


16

In [97]:
practice.nbytes

128

### Accessing/ Changing specific elements

In [19]:
a = np.array([[1, 2, 3,  4,  5,  6,  7],
              [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [20]:
# Get a specific element
a[1, 1]

9

In [21]:
# Get a specific row/ First value of first dimension and all values of second dimension
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [22]:
# Get a specific column/ All values of first dimension and third value of second dimension
a[:, 2]

array([ 3, 10])

In [23]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [24]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [25]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


3-dim example

In [145]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)
print(b.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


In [144]:
# Get specific element
b[0,1,1]

4

In [147]:
# Replace 
b[:,1,:] = [[9,9],[8,8]]
#b[:,1,:]

In [29]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

In [129]:
practic = np.array([[11, 22, 33,  44, 55,  66,  77] ,
                    [88, 99, 1010, 1111, 1212, 1313, 1414]])
practic

array([[  11,   22,   33,   44,   55,   66,   77],
       [  88,   99, 1010, 1111, 1212, 1313, 1414]])

In [130]:
practic [1,1]

99

In [131]:
practic [:,0]

array([11, 88])

In [132]:
practic [1,:]

array([  88,   99, 1010, 1111, 1212, 1313, 1414])

In [133]:
practic [0, 1:-1:2]

array([22, 44, 66])

In [134]:
practic [0,3]=19

In [135]:
practic

array([[  11,   22,   33,   19,   55,   66,   77],
       [  88,   99, 1010, 1111, 1212, 1313, 1414]])

In [140]:
practic [-1,-5]=1000

In [141]:
practic

array([[  11,   22, 1000,   19,   55,   66,   77],
       [  88,   99, 1000, 1111, 1212, 1313, 1414]])

### Initializing Different Types of Arrays

In [30]:
# All 0s matrix     what is shalow copy
z_mat = np.zeros((2,3))
z_mat

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
# All 1's Tensor
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [32]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [122]:
np.full((6,7),4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [33]:
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

In [34]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [35]:
# Random decimal number
np.random.rand()

0.5975634733980929

In [36]:
# Random decimal numbers array
np.random.rand(4,2)

array([[0.29773433, 0.11203154],
       [0.2163212 , 0.5432119 ],
       [0.8258676 , 0.63948876],
       [0.97802953, 0.45240859]])

In [37]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[ 6, -3,  7],
       [ 7, -1, -3],
       [ 3,  3, -1]])

In [38]:
# The identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [124]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

## In numpy axis = 1 by default. 
## axis = 0 along the rows,
## axis = 1 along the columns. 

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [40]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!

In [41]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(a)

[100   2   3]


In [42]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)

[1 2 3]


## Mathematics Functions

### Element-wise operations

In [43]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [44]:
a + 2

array([3, 4, 5, 6])

In [45]:
a - 2

array([-1,  0,  1,  2])

In [46]:
a * 2

array([2, 4, 6, 8])

In [47]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [48]:
a * a # Element wise multiplication

array([ 1,  4,  9, 16])

In [49]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [50]:
a ** 2

array([ 1,  4,  9, 16])

In [51]:
# Take the sin
degrees = 360
radians = (degrees * np.pi)/180
print(radians)
np.cos(radians) # Basically the method is used for radian, that's why we need to convert degree to radians first.


6.283185307179586


1.0

In [52]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

##### Linear Algebra

In [148]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [149]:
# Find the determinant
c = np.identity(3)
print(c)
det_v = np.linalg.det(c)
print(det_v)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
1.0


In [55]:
# Find Trace (Return the sum along diagonals of the array.)
trace_val = np.trace(c)
print(trace_val)


3.0


In [56]:
e_mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
e_mat.shape

(3, 3)

In [57]:
# Eigenvalues 
np.linalg.eigvals(e_mat)

array([ 1.61168440e+01, -1.11684397e+00, -3.38433605e-16])

In [58]:
ab = np.array([[1,1,3],[1,2,1],[1,1,2]])

# Inverse
np.linalg.inv(ab)

array([[-3., -1.,  5.],
       [ 1.,  1., -2.],
       [ 1., -0., -1.]])

##### Statistics

In [59]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
np.min(stats)

1

In [61]:
np.max(stats, axis=1)

array([3, 6])

In [62]:
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizing Arrays

In [63]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
print("Shape: ", before.shape)

print("_______________\n")

after = before.reshape((4,2))
print(after)
print("Shape: ", after.shape)

[[1 2 3 4]
 [5 6 7 8]]
Shape:  (2, 4)
_______________

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Shape:  (4, 2)


In [64]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [65]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous
##### Load Data from File

In [66]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


##### Boolean Masking and Advanced Indexing

In [67]:
~((filedata > 50) & (filedata < 100))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [68]:
filedata[~((filedata > 50) & (filedata < 100))]

array([  1,  13,  21,  11, 196,   4,   3,  34,   6,   7,   8,   0,   1,
         2,   3,   4,   5,   3,  42,  12,  33, 766,   4,   6,   4,   3,
         4,   5,   6,   7,   0,  11,  12,   1,  22,  33,  11, 999,  11,
         2,   1,   0,   1,   2,   9,   8,   7,   1], dtype=int32)

In [69]:
# Python way to make copy from list/dictionaly/tuple etc
# mlist = [x for x in filedata]
# mlist