In [10]:
import pandas as pd
import numpy as np
from collections import Counter

In [11]:
df = pd.read_csv("fruit_data_with_colors.txt",delimiter = "\t")

In [12]:
df.head()

fruit_label fruit_name fruit_subtype  mass  width  height  color_score
0            1      apple  granny_smith   192    8.4     7.3         0.55
1            1      apple  granny_smith   180    8.0     6.8         0.59
2            1      apple  granny_smith   176    7.4     7.2         0.60
3            2   mandarin      mandarin    86    6.2     4.7         0.80
4            2   mandarin      mandarin    84    6.0     4.6         0.79

In [13]:
df.drop({'fruit_label','fruit_name','fruit_subtype'},axis=1,inplace=True)

In [14]:
df.head()

mass  width  height  color_score
0   192    8.4     7.3         0.55
1   180    8.0     6.8         0.59
2   176    7.4     7.2         0.60
3    86    6.2     4.7         0.80
4    84    6.0     4.6         0.79

In [15]:
x=np.array(df)

In [16]:
x[:10]

array([[192.  ,   8.4 ,   7.3 ,   0.55],
       [180.  ,   8.  ,   6.8 ,   0.59],
       [176.  ,   7.4 ,   7.2 ,   0.6 ],
       [ 86.  ,   6.2 ,   4.7 ,   0.8 ],
       [ 84.  ,   6.  ,   4.6 ,   0.79],
       [ 80.  ,   5.8 ,   4.3 ,   0.77],
       [ 80.  ,   5.9 ,   4.3 ,   0.81],
       [ 76.  ,   5.8 ,   4.  ,   0.81],
       [178.  ,   7.1 ,   7.8 ,   0.92],
       [172.  ,   7.4 ,   7.  ,   0.89]])

In [44]:
X = df[["mass","width","height"]]

#### x[:10]

In [46]:
Y = df["fruit_label"]

In [47]:
trainX = np.array(X[:50])
trainY = np.array(Y[:50])
testX = np.array(X[50:])
testY = np.array(Y[50:])


In [48]:
print(df)

    fruit_label fruit_name     fruit_subtype   mass  width  height  \
0             1      apple      granny_smith    192    8.4     7.3   
1             1      apple      granny_smith    180    8.0     6.8   
2             1      apple      granny_smith    176    7.4     7.2   
3             2   mandarin          mandarin     86    6.2     4.7   
4             2   mandarin          mandarin     84    6.0     4.6   
5             2   mandarin          mandarin     80    5.8     4.3   
6             2   mandarin          mandarin     80    5.9     4.3   
7             2   mandarin          mandarin     76    5.8     4.0   
8             1      apple          braeburn    178    7.1     7.8   
9             1      apple          braeburn    172    7.4     7.0   
10            1      apple          braeburn    166    6.9     7.3   
11            1      apple          braeburn    172    7.1     7.6   
12            1      apple          braeburn    154    7.0     7.1   
13            1     

In [49]:
class KNN:
    def __init__(self,k = 1):
        self.k = k
        
    def euclidian_distance(self,query,X):
        difference = np.array(X) - np.array(query)
        sqrd_diff = np.square(difference)
        sum_sqrd_diff = np.sum(sqrd_diff, axis = 1)
        distance = np.sqrt(sum_sqrd_diff)
        return distance
    
    def nearest_neighbours(self,distance):
        return np.argsort(distance)[:self.k]
    
    def predict(self,query,trainX,trainY):
        ed = self.euclidian_distance(query,trainX)
        nn = self.nearest_neighbours(ed)
        labels_nn = list(trainY[nn])
        return max(labels_nn, key = labels_nn.count) 

In [50]:
classifier = KNN(4)

In [51]:
predictions = [classifier.predict(x,trainX,trainY) for x in testX]

In [52]:
predictions

[3, 3, 3, 3, 3, 3, 3, 3, 3]

In [53]:
testY

array([4, 4, 4, 4, 4, 4, 4, 4, 4], dtype=int64)

In [54]:
df = pd.read_csv("fruit_data_with_colors.txt",delimiter = "\t")

In [55]:
X = np.array(df[["mass","width","height","color_score"]])

In [56]:
  X.shape

(59, 4)

In [57]:
K = 4

In [58]:
centroidIndex = np.random.randint(0,58,(4,))

In [59]:
centroidIndex

array([17, 12, 47, 11])

In [60]:
centroids = X[centroidIndex]

In [61]:
centroids

array([[168.  ,   7.5 ,   7.6 ,   0.73],
       [154.  ,   7.  ,   7.1 ,   0.88],
       [196.  ,   7.3 ,   9.7 ,   0.72],
       [172.  ,   7.1 ,   7.6 ,   0.92]])

In [62]:
X_ = np.delete(X,centroidIndex, axis = 0)

In [63]:
clusters = [[],[],[],[]]
clusters[0].append(centroids[0])
clusters[1].append(centroids[1])
clusters[2].append(centroids[2])
clusters[3].append(centroids[3])

In [64]:
def euclidian_distance(query,X):
        difference = np.array(X) - np.array(query)
        sqrd_diff = np.square(difference)
        sum_sqrd_diff = np.sum(sqrd_diff, axis = 1)
        distance = np.sqrt(sum_sqrd_diff)
        return distance

In [65]:
for x in X_:
    id = np.argmin(euclidian_distance(x,centroids))
    clusters[id].append(x)

In [66]:
len(clusters[0])

7

In [67]:
len(clusters[1])

31

In [68]:
len(clusters[2])

14

In [69]:
len(clusters[3])

7

In [70]:
centroids[0] = np.mean(clusters[0],axis = 0)