In [1]:
import pandas as pd
import numpy as np

In [2]:
df= pd.read_csv('fruit_data_with_colors.txt',delimiter='\t')
df.drop("fruit_name", axis=1, inplace=True)
df.drop("fruit_subtype", axis=1, inplace=True)

In [3]:
df

fruit_label   mass  width  height  color_score
0             1    192    8.4     7.3         0.55
1             1    180    8.0     6.8         0.59
2             1    176    7.4     7.2         0.60
3             2     86    6.2     4.7         0.80
4             2     84    6.0     4.6         0.79
5             2     80    5.8     4.3         0.77
6             2     80    5.9     4.3         0.81
7             2     76    5.8     4.0         0.81
8             1    178    7.1     7.8         0.92
9             1    172    7.4     7.0         0.89
10            1    166    6.9     7.3         0.93
11            1    172    7.1     7.6         0.92
12            1    154    7.0     7.1         0.88
13            1    164    7.3     7.7         0.70
14            1    152    7.6     7.3         0.69
15            1    156    7.7     7.1         0.69
16            1   1000    7.6     7.5         0.67
17            1    168    7.5     7.6         0.73
18            1    162    7.5     7.1         0.83
19            1    162    7.4     7.2         0.85
20            1    160    7.5     7.5         0.86
21            1    156    7.4     7.4         0.84
22            1    140    7.3     7.1         0.87
23            1    170    7.6     7.9         0.88
24            3    342    9.0     9.4         0.75
25            3    356    9.2     9.2         0.75
26            3    362    9.6     9.2         0.74
27            3    204    7.5     9.2         0.77
28            3    140    6.7     7.1         0.72
29            3    160    7.0     7.4         0.81
30            3    158    7.1     7.5         0.79
31            3    210    7.8     8.0         0.82
32            3    164    7.2     7.0         0.80
33            3    190    7.5     8.1         0.74
34            3    142    7.6     7.8         0.75
35            3    150    7.1     7.9         0.75
36            3    160    7.1     7.6         0.76
37            3    154    7.3     7.3         0.79
38            3    158    7.2     7.8         0.77
39            3    154    7.3     7.5         0.76
40            3  30000    7.1     7.5         0.78
41            3    180    7.6     8.2         0.79
42            3    154    7.2     7.2         0.82
43            4    194    7.2    10.3         0.70
44            4    200    7.3    10.5         0.72
45            4    186    7.2     9.2         0.72
46            4    216    7.3    10.2         0.71
47            4    196    7.3     9.7         0.72
48            4    174    7.3    10.1         0.72
49            4    132    5.8     8.7         0.73
50            4    130    6.0     8.2         0.71
51            4    116    6.0     7.5         0.72
52            4    118    5.9     8.0         0.72
53            4    120    6.0     8.4         0.74
54            4    116    6.1     8.5         0.71
55            4    116    6.3     7.7         0.72
56            4    116    5.9     8.1         0.73
57            4    152    6.5     8.5         0.72
58            4    118    6.1     8.1         0.70

In [4]:
train=df[:50]
train

fruit_label   mass  width  height  color_score
0             1    192    8.4     7.3         0.55
1             1    180    8.0     6.8         0.59
2             1    176    7.4     7.2         0.60
3             2     86    6.2     4.7         0.80
4             2     84    6.0     4.6         0.79
5             2     80    5.8     4.3         0.77
6             2     80    5.9     4.3         0.81
7             2     76    5.8     4.0         0.81
8             1    178    7.1     7.8         0.92
9             1    172    7.4     7.0         0.89
10            1    166    6.9     7.3         0.93
11            1    172    7.1     7.6         0.92
12            1    154    7.0     7.1         0.88
13            1    164    7.3     7.7         0.70
14            1    152    7.6     7.3         0.69
15            1    156    7.7     7.1         0.69
16            1   1000    7.6     7.5         0.67
17            1    168    7.5     7.6         0.73
18            1    162    7.5     7.1         0.83
19            1    162    7.4     7.2         0.85
20            1    160    7.5     7.5         0.86
21            1    156    7.4     7.4         0.84
22            1    140    7.3     7.1         0.87
23            1    170    7.6     7.9         0.88
24            3    342    9.0     9.4         0.75
25            3    356    9.2     9.2         0.75
26            3    362    9.6     9.2         0.74
27            3    204    7.5     9.2         0.77
28            3    140    6.7     7.1         0.72
29            3    160    7.0     7.4         0.81
30            3    158    7.1     7.5         0.79
31            3    210    7.8     8.0         0.82
32            3    164    7.2     7.0         0.80
33            3    190    7.5     8.1         0.74
34            3    142    7.6     7.8         0.75
35            3    150    7.1     7.9         0.75
36            3    160    7.1     7.6         0.76
37            3    154    7.3     7.3         0.79
38            3    158    7.2     7.8         0.77
39            3    154    7.3     7.5         0.76
40            3  30000    7.1     7.5         0.78
41            3    180    7.6     8.2         0.79
42            3    154    7.2     7.2         0.82
43            4    194    7.2    10.3         0.70
44            4    200    7.3    10.5         0.72
45            4    186    7.2     9.2         0.72
46            4    216    7.3    10.2         0.71
47            4    196    7.3     9.7         0.72
48            4    174    7.3    10.1         0.72
49            4    132    5.8     8.7         0.73

In [5]:
test=df[50:]
df


fruit_label   mass  width  height  color_score
0             1    192    8.4     7.3         0.55
1             1    180    8.0     6.8         0.59
2             1    176    7.4     7.2         0.60
3             2     86    6.2     4.7         0.80
4             2     84    6.0     4.6         0.79
5             2     80    5.8     4.3         0.77
6             2     80    5.9     4.3         0.81
7             2     76    5.8     4.0         0.81
8             1    178    7.1     7.8         0.92
9             1    172    7.4     7.0         0.89
10            1    166    6.9     7.3         0.93
11            1    172    7.1     7.6         0.92
12            1    154    7.0     7.1         0.88
13            1    164    7.3     7.7         0.70
14            1    152    7.6     7.3         0.69
15            1    156    7.7     7.1         0.69
16            1   1000    7.6     7.5         0.67
17            1    168    7.5     7.6         0.73
18            1    162    7.5     7.1         0.83
19            1    162    7.4     7.2         0.85
20            1    160    7.5     7.5         0.86
21            1    156    7.4     7.4         0.84
22            1    140    7.3     7.1         0.87
23            1    170    7.6     7.9         0.88
24            3    342    9.0     9.4         0.75
25            3    356    9.2     9.2         0.75
26            3    362    9.6     9.2         0.74
27            3    204    7.5     9.2         0.77
28            3    140    6.7     7.1         0.72
29            3    160    7.0     7.4         0.81
30            3    158    7.1     7.5         0.79
31            3    210    7.8     8.0         0.82
32            3    164    7.2     7.0         0.80
33            3    190    7.5     8.1         0.74
34            3    142    7.6     7.8         0.75
35            3    150    7.1     7.9         0.75
36            3    160    7.1     7.6         0.76
37            3    154    7.3     7.3         0.79
38            3    158    7.2     7.8         0.77
39            3    154    7.3     7.5         0.76
40            3  30000    7.1     7.5         0.78
41            3    180    7.6     8.2         0.79
42            3    154    7.2     7.2         0.82
43            4    194    7.2    10.3         0.70
44            4    200    7.3    10.5         0.72
45            4    186    7.2     9.2         0.72
46            4    216    7.3    10.2         0.71
47            4    196    7.3     9.7         0.72
48            4    174    7.3    10.1         0.72
49            4    132    5.8     8.7         0.73
50            4    130    6.0     8.2         0.71
51            4    116    6.0     7.5         0.72
52            4    118    5.9     8.0         0.72
53            4    120    6.0     8.4         0.74
54            4    116    6.1     8.5         0.71
55            4    116    6.3     7.7         0.72
56            4    116    5.9     8.1         0.73
57            4    152    6.5     8.5         0.72
58            4    118    6.1     8.1         0.70

In [6]:
X=df[["mass","width","height","color_score"]]

In [7]:
Y=df[["fruit_label"]]

In [8]:
trainX=np.array(X[:50])
trainY=np.array(Y[:50])
testX=np.array(Y[50:])
testY=np.array(Y[50:])

In [9]:
X

mass  width  height  color_score
0     192    8.4     7.3         0.55
1     180    8.0     6.8         0.59
2     176    7.4     7.2         0.60
3      86    6.2     4.7         0.80
4      84    6.0     4.6         0.79
5      80    5.8     4.3         0.77
6      80    5.9     4.3         0.81
7      76    5.8     4.0         0.81
8     178    7.1     7.8         0.92
9     172    7.4     7.0         0.89
10    166    6.9     7.3         0.93
11    172    7.1     7.6         0.92
12    154    7.0     7.1         0.88
13    164    7.3     7.7         0.70
14    152    7.6     7.3         0.69
15    156    7.7     7.1         0.69
16   1000    7.6     7.5         0.67
17    168    7.5     7.6         0.73
18    162    7.5     7.1         0.83
19    162    7.4     7.2         0.85
20    160    7.5     7.5         0.86
21    156    7.4     7.4         0.84
22    140    7.3     7.1         0.87
23    170    7.6     7.9         0.88
24    342    9.0     9.4         0.75
25    356    9.2     9.2         0.75
26    362    9.6     9.2         0.74
27    204    7.5     9.2         0.77
28    140    6.7     7.1         0.72
29    160    7.0     7.4         0.81
30    158    7.1     7.5         0.79
31    210    7.8     8.0         0.82
32    164    7.2     7.0         0.80
33    190    7.5     8.1         0.74
34    142    7.6     7.8         0.75
35    150    7.1     7.9         0.75
36    160    7.1     7.6         0.76
37    154    7.3     7.3         0.79
38    158    7.2     7.8         0.77
39    154    7.3     7.5         0.76
40  30000    7.1     7.5         0.78
41    180    7.6     8.2         0.79
42    154    7.2     7.2         0.82
43    194    7.2    10.3         0.70
44    200    7.3    10.5         0.72
45    186    7.2     9.2         0.72
46    216    7.3    10.2         0.71
47    196    7.3     9.7         0.72
48    174    7.3    10.1         0.72
49    132    5.8     8.7         0.73
50    130    6.0     8.2         0.71
51    116    6.0     7.5         0.72
52    118    5.9     8.0         0.72
53    120    6.0     8.4         0.74
54    116    6.1     8.5         0.71
55    116    6.3     7.7         0.72
56    116    5.9     8.1         0.73
57    152    6.5     8.5         0.72
58    118    6.1     8.1         0.70

In [10]:
Y

fruit_label
0             1
1             1
2             1
3             2
4             2
5             2
6             2
7             2
8             1
9             1
10            1
11            1
12            1
13            1
14            1
15            1
16            1
17            1
18            1
19            1
20            1
21            1
22            1
23            1
24            3
25            3
26            3
27            3
28            3
29            3
30            3
31            3
32            3
33            3
34            3
35            3
36            3
37            3
38            3
39            3
40            3
41            3
42            3
43            4
44            4
45            4
46            4
47            4
48            4
49            4
50            4
51            4
52            4
53            4
54            4
55            4
56            4
57            4
58            4

In [18]:
class KNN:
    def __init__(self,k = 1):
        self.k = k
        
    def euclidian_distance(self,query,X):
        difference = np.array(X) - np.array(query)
        sqrd_diff = np.square(difference)
        sum_sqrd_diff = np.sum(sqrd_diff, axis = 1)
        distance = np.sqrt(sum_sqrd_diff)
        return distance
    
    def nearest_neighbours(self,distance):
        return np.argsort(distance)[:self.k]
    
    def predict(self,query,trainX,trainY):
        ed = self.euclidian_distance(query,trainX)
        nn = self.nearest_neighbours(ed)
        labels_nn = list(trainY[nn])
        return max(labels_nn, key = labels_nn.count) 
    

In [19]:
classifier=KNN(1)

In [20]:
predictions = [classifier.predict(x,trainX,trainY) for x in testX]

In [21]:
predictions

[array([2], dtype=int64),
 array([2], dtype=int64),
 array([2], dtype=int64),
 array([2], dtype=int64),
 array([2], dtype=int64),
 array([2], dtype=int64),
 array([2], dtype=int64),
 array([2], dtype=int64),
 array([2], dtype=int64)]

In [ ]:
#confusing matrix
#Accuracy
#sikitlab
from sklearn import metrics