### **TASK 1**
Use the implementation of perceptron from the last lab manual and model the truth table of XOR.

![XOR](./XOR.png "XOR")


### **TASK 2**
1. Import the diabetes dataset. You can find data description in the description file.
2. Use pandas plots to have a look and feel of the different attributes of the data.
3. Apply perceptron algorithm to model the data distribution.
4. Use mean squared error as your cost/ error function.
5. Use the below given derivatives to find gradients of each W.

![MSE](./MSE.png "MSE")

![MSE derivative](./derivativeMSE.png "MSE derivative")


In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [3]:
df = pd.DataFrame(np.array([[0,0,0],[0,1,1],[1,0,1],[1,1,0]]),columns=['x1','x2','label'])
df

x1  x2  label
0   0   0      0
1   0   1      1
2   1   0      1
3   1   1      0

In [3]:
arr = np.array(df)
arr

array([[0, 0, 0],
       [0, 1, 1],
       [1, 0, 1],
       [1, 1, 0]])

In [4]:
X=np.array(df[['x1','x2']])
X=np.array(X)
X

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [5]:
Y=np.array(df['label'])
Y=np.array(Y)
Y

array([0, 1, 1, 0])

In [6]:
print("Features")
print(X)
print("Label")
print(Y)


Features
[[0 0]
 [0 1]
 [1 0]
 [1 1]]
Label
[0 1 1 0]


In [7]:
X =X.T

In [8]:
X.shape

(2, 4)

In [9]:
W = np.random.rand(2,1)
b = np.random.rand()

In [10]:
print(W)
print(b)

[[0.42731205]
 [0.12515294]]
0.9203324386641762


In [11]:
np.expand_dims(Y , axis=0).shape

(1, 4)

In [12]:
def sigmoid(z):
    return 1/(1 + np.exp(-z))

In [19]:
Z.shape

(1, 4)

In [18]:
A.shape

(4,)

In [17]:
from sklearn.metrics import log_loss
J = log_loss(Y,A)

In [16]:
alpha = 0.001
for i in range(10):
    #forward pass
    Z=np.dot(W.T,X) +b
    A=sigmoid(Z)
    A=np.where(A<0.5,0,1)
    A=A.squeeze()
    #Backword Pass
    J=log_loss(Y,A)
    print(J)
    dz = A - Y
    dz=np.expand_dims(dz,axis=0)
    dw=np.dot(X,dz.T)/X.shape[0]
    db=np.sum(dz,axis=1)/X.shape[0]
    W=W-alpha * dw
    b = b - alpha * db
    


    

17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
